# -*- coding: utf-8 -*-
"""Linear Regression Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYa6RzScj4X6vmeynef9qMGQvQqzGEb8
"""

import numpy as np

import matplotlib.pyplot as plt

x_train=np.array([1.5, 2.6, 3.2, 4.9, 7.2])

y_train=np.array([300.0, 500.0, 700.0, 200.0, 400.0])

print(f"x_train (size): {x_train}")
print(f"y_train (price): {y_train}")

w= 100
b=0

def compute_model_output(x,w,b):
  m=x.shape[0]
  f_wb = np.zeros(m)

  for i in range(m):
    f_wb[i] = w * x[i] + b

  return f_wb

predicted_val = compute_model_output(x_train , w , b)

plt.scatter(x_train, y_train, marker='x', c='r', label='Actual Data')

plt.plot(x_train, predicted_val, c='b', label='Our prediction')

plt.title("House Price")
plt.ylabel("Price in dollers")
plt.xlabel("Size of house")
plt.legend()
plt.grid(True)
plt.show()

