{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMYQu9E8gi/e21enUUD+PKs",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Abhishek844506/Machine-Learning/blob/main/Multiple_linear_reg_with_sklearn.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 51,
      "metadata": {
        "id": "V0bi3ZT7EVpk"
      },
      "outputs": [],
      "source": [
        "import numpy as np"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import matplotlib.pyplot as plt"
      ],
      "metadata": {
        "id": "ToKVEzISEbsz"
      },
      "execution_count": 52,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.linear_model import LinearRegression"
      ],
      "metadata": {
        "id": "6KPEzThCEfUP"
      },
      "execution_count": 53,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.model_selection import train_test_split"
      ],
      "metadata": {
        "id": "bMuaTa_EMXAq"
      },
      "execution_count": 54,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "x = np.array([\n",
        "    [1000, 2, 1, 10],\n",
        "    [1500, 3, 2, 8],\n",
        "    [2000, 3, 2, 5],\n",
        "    [2500, 4, 2, 3],\n",
        "    [3000, 4, 3, 2],\n",
        "    [1800, 3, 1, 12],\n",
        "    [2200, 3, 2, 7],\n",
        "    [2700, 4, 2, 4]\n",
        "])\n",
        "y = np.array([50, 70, 90, 110, 130, 80, 95, 120])"
      ],
      "metadata": {
        "id": "5Qu5gj0eEmbZ"
      },
      "execution_count": 77,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.50, random_state=5)"
      ],
      "metadata": {
        "id": "3F79efUJMjhz"
      },
      "execution_count": 100,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "model = LinearRegression()"
      ],
      "metadata": {
        "id": "So0PjjQkEqof"
      },
      "execution_count": 101,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "model.fit(x_train, y_train)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 80
        },
        "id": "tIWxgWAgFSPJ",
        "outputId": "37f0b0fb-3df8-4e65-aff4-7529db5e12ac"
      },
      "execution_count": 102,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "LinearRegression()"
            ],
            "text/html": [
              "<style>#sk-container-id-10 {\n",
              "  /* Definition of color scheme common for light and dark mode */\n",
              "  --sklearn-color-text: #000;\n",
              "  --sklearn-color-text-muted: #666;\n",
              "  --sklearn-color-line: gray;\n",
              "  /* Definition of color scheme for unfitted estimators */\n",
              "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
              "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
              "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
              "  --sklearn-color-unfitted-level-3: chocolate;\n",
              "  /* Definition of color scheme for fitted estimators */\n",
              "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
              "  --sklearn-color-fitted-level-1: #d4ebff;\n",
              "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
              "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
              "\n",
              "  /* Specific color for light theme */\n",
              "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
              "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
              "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
              "  --sklearn-color-icon: #696969;\n",
              "\n",
              "  @media (prefers-color-scheme: dark) {\n",
              "    /* Redefinition of color scheme for dark theme */\n",
              "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
              "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
              "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
              "    --sklearn-color-icon: #878787;\n",
              "  }\n",
              "}\n",
              "\n",
              "#sk-container-id-10 {\n",
              "  color: var(--sklearn-color-text);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 pre {\n",
              "  padding: 0;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 input.sk-hidden--visually {\n",
              "  border: 0;\n",
              "  clip: rect(1px 1px 1px 1px);\n",
              "  clip: rect(1px, 1px, 1px, 1px);\n",
              "  height: 1px;\n",
              "  margin: -1px;\n",
              "  overflow: hidden;\n",
              "  padding: 0;\n",
              "  position: absolute;\n",
              "  width: 1px;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-dashed-wrapped {\n",
              "  border: 1px dashed var(--sklearn-color-line);\n",
              "  margin: 0 0.4em 0.5em 0.4em;\n",
              "  box-sizing: border-box;\n",
              "  padding-bottom: 0.4em;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-container {\n",
              "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
              "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
              "     so we also need the `!important` here to be able to override the\n",
              "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
              "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
              "  display: inline-block !important;\n",
              "  position: relative;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-text-repr-fallback {\n",
              "  display: none;\n",
              "}\n",
              "\n",
              "div.sk-parallel-item,\n",
              "div.sk-serial,\n",
              "div.sk-item {\n",
              "  /* draw centered vertical line to link estimators */\n",
              "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
              "  background-size: 2px 100%;\n",
              "  background-repeat: no-repeat;\n",
              "  background-position: center center;\n",
              "}\n",
              "\n",
              "/* Parallel-specific style estimator block */\n",
              "\n",
              "#sk-container-id-10 div.sk-parallel-item::after {\n",
              "  content: \"\";\n",
              "  width: 100%;\n",
              "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
              "  flex-grow: 1;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-parallel {\n",
              "  display: flex;\n",
              "  align-items: stretch;\n",
              "  justify-content: center;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  position: relative;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-parallel-item {\n",
              "  display: flex;\n",
              "  flex-direction: column;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-parallel-item:first-child::after {\n",
              "  align-self: flex-end;\n",
              "  width: 50%;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-parallel-item:last-child::after {\n",
              "  align-self: flex-start;\n",
              "  width: 50%;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-parallel-item:only-child::after {\n",
              "  width: 0;\n",
              "}\n",
              "\n",
              "/* Serial-specific style estimator block */\n",
              "\n",
              "#sk-container-id-10 div.sk-serial {\n",
              "  display: flex;\n",
              "  flex-direction: column;\n",
              "  align-items: center;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  padding-right: 1em;\n",
              "  padding-left: 1em;\n",
              "}\n",
              "\n",
              "\n",
              "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
              "clickable and can be expanded/collapsed.\n",
              "- Pipeline and ColumnTransformer use this feature and define the default style\n",
              "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
              "*/\n",
              "\n",
              "/* Pipeline and ColumnTransformer style (default) */\n",
              "\n",
              "#sk-container-id-10 div.sk-toggleable {\n",
              "  /* Default theme specific background. It is overwritten whether we have a\n",
              "  specific estimator or a Pipeline/ColumnTransformer */\n",
              "  background-color: var(--sklearn-color-background);\n",
              "}\n",
              "\n",
              "/* Toggleable label */\n",
              "#sk-container-id-10 label.sk-toggleable__label {\n",
              "  cursor: pointer;\n",
              "  display: flex;\n",
              "  width: 100%;\n",
              "  margin-bottom: 0;\n",
              "  padding: 0.5em;\n",
              "  box-sizing: border-box;\n",
              "  text-align: center;\n",
              "  align-items: start;\n",
              "  justify-content: space-between;\n",
              "  gap: 0.5em;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 label.sk-toggleable__label .caption {\n",
              "  font-size: 0.6rem;\n",
              "  font-weight: lighter;\n",
              "  color: var(--sklearn-color-text-muted);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 label.sk-toggleable__label-arrow:before {\n",
              "  /* Arrow on the left of the label */\n",
              "  content: \"▸\";\n",
              "  float: left;\n",
              "  margin-right: 0.25em;\n",
              "  color: var(--sklearn-color-icon);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 label.sk-toggleable__label-arrow:hover:before {\n",
              "  color: var(--sklearn-color-text);\n",
              "}\n",
              "\n",
              "/* Toggleable content - dropdown */\n",
              "\n",
              "#sk-container-id-10 div.sk-toggleable__content {\n",
              "  max-height: 0;\n",
              "  max-width: 0;\n",
              "  overflow: hidden;\n",
              "  text-align: left;\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-toggleable__content.fitted {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-toggleable__content pre {\n",
              "  margin: 0.2em;\n",
              "  border-radius: 0.25em;\n",
              "  color: var(--sklearn-color-text);\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-toggleable__content.fitted pre {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
              "  /* Expand drop-down */\n",
              "  max-height: 200px;\n",
              "  max-width: 100%;\n",
              "  overflow: auto;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
              "  content: \"▾\";\n",
              "}\n",
              "\n",
              "/* Pipeline/ColumnTransformer-specific style */\n",
              "\n",
              "#sk-container-id-10 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  color: var(--sklearn-color-text);\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "/* Estimator-specific style */\n",
              "\n",
              "/* Colorize estimator box */\n",
              "#sk-container-id-10 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-label label.sk-toggleable__label,\n",
              "#sk-container-id-10 div.sk-label label {\n",
              "  /* The background is the default theme color */\n",
              "  color: var(--sklearn-color-text-on-default-background);\n",
              "}\n",
              "\n",
              "/* On hover, darken the color of the background */\n",
              "#sk-container-id-10 div.sk-label:hover label.sk-toggleable__label {\n",
              "  color: var(--sklearn-color-text);\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "/* Label box, darken color on hover, fitted */\n",
              "#sk-container-id-10 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
              "  color: var(--sklearn-color-text);\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "/* Estimator label */\n",
              "\n",
              "#sk-container-id-10 div.sk-label label {\n",
              "  font-family: monospace;\n",
              "  font-weight: bold;\n",
              "  display: inline-block;\n",
              "  line-height: 1.2em;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-label-container {\n",
              "  text-align: center;\n",
              "}\n",
              "\n",
              "/* Estimator-specific */\n",
              "#sk-container-id-10 div.sk-estimator {\n",
              "  font-family: monospace;\n",
              "  border: 1px dotted var(--sklearn-color-border-box);\n",
              "  border-radius: 0.25em;\n",
              "  box-sizing: border-box;\n",
              "  margin-bottom: 0.5em;\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-estimator.fitted {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-0);\n",
              "}\n",
              "\n",
              "/* on hover */\n",
              "#sk-container-id-10 div.sk-estimator:hover {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-10 div.sk-estimator.fitted:hover {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
              "\n",
              "/* Common style for \"i\" and \"?\" */\n",
              "\n",
              ".sk-estimator-doc-link,\n",
              "a:link.sk-estimator-doc-link,\n",
              "a:visited.sk-estimator-doc-link {\n",
              "  float: right;\n",
              "  font-size: smaller;\n",
              "  line-height: 1em;\n",
              "  font-family: monospace;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  border-radius: 1em;\n",
              "  height: 1em;\n",
              "  width: 1em;\n",
              "  text-decoration: none !important;\n",
              "  margin-left: 0.5em;\n",
              "  text-align: center;\n",
              "  /* unfitted */\n",
              "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
              "  color: var(--sklearn-color-unfitted-level-1);\n",
              "}\n",
              "\n",
              ".sk-estimator-doc-link.fitted,\n",
              "a:link.sk-estimator-doc-link.fitted,\n",
              "a:visited.sk-estimator-doc-link.fitted {\n",
              "  /* fitted */\n",
              "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
              "  color: var(--sklearn-color-fitted-level-1);\n",
              "}\n",
              "\n",
              "/* On hover */\n",
              "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
              ".sk-estimator-doc-link:hover,\n",
              "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
              ".sk-estimator-doc-link:hover {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-3);\n",
              "  color: var(--sklearn-color-background);\n",
              "  text-decoration: none;\n",
              "}\n",
              "\n",
              "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
              ".sk-estimator-doc-link.fitted:hover,\n",
              "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
              ".sk-estimator-doc-link.fitted:hover {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-3);\n",
              "  color: var(--sklearn-color-background);\n",
              "  text-decoration: none;\n",
              "}\n",
              "\n",
              "/* Span, style for the box shown on hovering the info icon */\n",
              ".sk-estimator-doc-link span {\n",
              "  display: none;\n",
              "  z-index: 9999;\n",
              "  position: relative;\n",
              "  font-weight: normal;\n",
              "  right: .2ex;\n",
              "  padding: .5ex;\n",
              "  margin: .5ex;\n",
              "  width: min-content;\n",
              "  min-width: 20ex;\n",
              "  max-width: 50ex;\n",
              "  color: var(--sklearn-color-text);\n",
              "  box-shadow: 2pt 2pt 4pt #999;\n",
              "  /* unfitted */\n",
              "  background: var(--sklearn-color-unfitted-level-0);\n",
              "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
              "}\n",
              "\n",
              ".sk-estimator-doc-link.fitted span {\n",
              "  /* fitted */\n",
              "  background: var(--sklearn-color-fitted-level-0);\n",
              "  border: var(--sklearn-color-fitted-level-3);\n",
              "}\n",
              "\n",
              ".sk-estimator-doc-link:hover span {\n",
              "  display: block;\n",
              "}\n",
              "\n",
              "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
              "\n",
              "#sk-container-id-10 a.estimator_doc_link {\n",
              "  float: right;\n",
              "  font-size: 1rem;\n",
              "  line-height: 1em;\n",
              "  font-family: monospace;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  border-radius: 1rem;\n",
              "  height: 1rem;\n",
              "  width: 1rem;\n",
              "  text-decoration: none;\n",
              "  /* unfitted */\n",
              "  color: var(--sklearn-color-unfitted-level-1);\n",
              "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 a.estimator_doc_link.fitted {\n",
              "  /* fitted */\n",
              "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
              "  color: var(--sklearn-color-fitted-level-1);\n",
              "}\n",
              "\n",
              "/* On hover */\n",
              "#sk-container-id-10 a.estimator_doc_link:hover {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-3);\n",
              "  color: var(--sklearn-color-background);\n",
              "  text-decoration: none;\n",
              "}\n",
              "\n",
              "#sk-container-id-10 a.estimator_doc_link.fitted:hover {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-3);\n",
              "}\n",
              "</style><div id=\"sk-container-id-10\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-10\" type=\"checkbox\" checked><label for=\"sk-estimator-id-10\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LinearRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.6/modules/generated/sklearn.linear_model.LinearRegression.html\">?<span>Documentation for LinearRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\"><pre>LinearRegression()</pre></div> </div></div></div></div>"
            ]
          },
          "metadata": {},
          "execution_count": 102
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(\"Parameters found by Sklearn\")\n",
        "print(f\"Weight:{model.coef_}\")\n",
        "print(f\"Bias: {model.intercept_:.2f}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "b3Nt3ta9FYrd",
        "outputId": "11f70ab7-f760-4d43-8228-c76c44ca784b"
      },
      "execution_count": 103,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Parameters found by Sklearn\n",
            "Weight:[ 0.03581392  2.31785056 -1.74803481 -0.48449335]\n",
            "Bias: 16.14\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "y_prediction= model.predict(x_test)"
      ],
      "metadata": {
        "id": "5EHz_fObF1Ca"
      },
      "execution_count": 104,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "print(\"\\n --- Predictions ---\")\n",
        "print(f\"Actual Prices: {y_test}\")\n",
        "print(f\"Prediction: {y_prediction}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dGnCWSq7GFKu",
        "outputId": "297a5466-0d4f-4f08-ef6c-42131b3a870f"
      },
      "execution_count": 105,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            " --- Predictions ---\n",
            "Actual Prices: [120  90 130  70]\n",
            "Prediction: [116.67829069  88.80620266 126.64341863  69.44576253]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "new_house = np.array([[2010, 13, 4, 33]])\n",
        "new_prediction = model.predict(new_house)[0]\n",
        "y_test_extended = np.append(y_test, np.nan)  # no actual price available\n",
        "y_prediction_extended = np.append(y_prediction, new_prediction)\n",
        "\n",
        "plt.figure(figsize=(20,6))\n",
        "x_indi = np.arange(len(y_test_extended))\n",
        "width=0.35\n",
        "\n",
        "\n",
        "plt.bar(x_indi - width/2, y_test_extended, width, label='Actual')\n",
        "plt.bar(x_indi + width/2, y_prediction_extended, width, label='Prediction')\n",
        "plt.xlabel('House')\n",
        "plt.ylabel('Price')\n",
        "plt.legend()\n",
        "plt.show()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 365
        },
        "id": "lq27ifSJGIp8",
        "outputId": "0fe821cf-3aff-48f4-813a-5ad12352ed2f"
      },
      "execution_count": 110,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 2000x600 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAABlkAAAINCAYAAAC9PhkkAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAAOOhJREFUeJzt3X+Yl3Wd7/HX8GsGkZkJlAEShKOkaP5IMZv0uKiz/qwFpdQNj2Ae3VOgGbUpe6UppRipEfkDK9Pc1dTaZM2fubTCqqiIi1dthtii4lHAVhkEL2BgvuePTt89cxSV24HvzPB4XNf3uvx+7vt7f983et1d+fT+3lWlUqkUAAAAAAAAtkq3Sg8AAAAAAADQGYksAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABfSo9AAdQWtra1555ZX07ds3VVVVlR4HAAAAAACooFKplDfffDODBw9Ot25bvl9FZEnyyiuvZMiQIZUeAwAAAAAA6ECWL1+e3XbbbYvbRZYkffv2TfKnP6za2toKTwMAAAAAAFTSmjVrMmTIkHI/2BKRJSn/RFhtba3IAgAAAAAAJMl7PmLEg+8BAAAAAAAKEFkAAAAAAAAKEFkAAAAAAAAK8EwWAAAAAAB4D5s3b05LS0ulx6CddO/ePT169HjPZ668F5EFAAAAAADexdq1a/Pyyy+nVCpVehTa0U477ZRBgwalV69ehY8hsgAAAAAAwBZs3rw5L7/8cnbaaafsuuuuH/jOByqvVCpl48aNee2117Js2bKMGDEi3boVe7qKyAIAAAAAAFvQ0tKSUqmUXXfdNb179670OLST3r17p2fPnnnxxRezcePG1NTUFDqOB98DAAAAAMB7cAdL11P07pU2x2iHOQAAAAAAAHY4IgsAAAAAAEABnskCAAAAAABbadiF927X73vhihO36/dtS1VVVbnrrrsyduzYSo/ygbmTBQAAAAAAuqgFCxake/fuOfHErYs0w4YNy8yZM7fNUF2IyAIAAAAAAF3UjTfemHPPPTfz58/PK6+8UulxuhyRBQAAAAAAuqC1a9fmjjvuyBe+8IWceOKJufnmm9ts/+Uvf5lDDjkkNTU12WWXXXLSSSclSUaPHp0XX3wxX/7yl1NVVZWqqqokySWXXJIDDzywzTFmzpyZYcOGld8vXLgwf/mXf5lddtkldXV1+Yu/+Is8/fTT2/I0K0pkAQAAAACALujOO+/M3nvvnb322iunn356fvzjH6dUKiVJ7r333px00kk54YQT8m//9m+ZO3duPv7xjydJfvGLX2S33XbLtGnT8uqrr+bVV19939/55ptvZsKECXnkkUfy+OOPZ8SIETnhhBPy5ptvbpNzrDQPvgcAAAAAgC7oxhtvzOmnn54kOe6449Lc3Jx58+Zl9OjRueyyy3Laaafl0ksvLe9/wAEHJEn69euX7t27p2/fvhk4cOBWfedRRx3V5v0PfvCD1NfXZ968efnUpz71Ac+o43EnCwAAAAAAdDFLlizJk08+mb/+679OkvTo0SOnnnpqbrzxxiTJ4sWLc/TRR7f7965cuTJnn312RowYkbq6utTW1mbt2rV56aWX2v27OgJ3sgAAAAAAQBdz4403ZtOmTRk8eHB5rVQqpbq6Otdcc0169+691cfs1q1b+efG/qylpaXN+wkTJuQ///M/873vfS+77757qqur09jYmI0bNxY7kQ7OnSwAAAAAANCFbNq0KbfcckuuuuqqLF68uPx65plnMnjw4Pz0pz/N/vvvn7lz527xGL169crmzZvbrO26665ZsWJFm9CyePHiNvs8+uijOe+883LCCSdk3333TXV1df74xz+26/l1JO5kAQCA7WjYhfdWegTewwtXnFjpEQAA4AO555578sYbb+Sss85KXV1dm23jxo3LjTfemO985zs5+uijs8cee+S0007Lpk2bct999+WCCy5IkgwbNizz58/Paaedlurq6uyyyy4ZPXp0XnvttcyYMSOf+cxn8sADD+T+++9PbW1t+fgjRozI3//932fUqFFZs2ZN/vZv/7bQXTOdhcgCAAAAAABbqSP/xzk33nhjmpqa3hZYkj9FlhkzZqRfv3752c9+lm9+85u54oorUltbmyOOOKK837Rp0/I3f/M32WOPPbJhw4aUSqWMHDky1113XS6//PJ885vfzLhx4/LVr341P/jBD9p89znnnJODDjooQ4YMyeWXX56vfvWr2+W8K6Gq9P//gNoOaM2aNamrq0tzc3Ob4gYAAO3NnSwdX0f+P8sAAGx/69evz7JlyzJ8+PDU1NRUehza0bv9vX2/3cAzWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAroUekBAAAAOpRL6io9Ae/lkuZKTwAAwP81ceLErF69OnPmzEmSjB49OgceeGBmzpxZ+JjtcYztRWQBAAAAAICttb3/45yt/A9NJk6cmJ/85CdJkp49e2bo0KE544wz8nd/93fp0WPbpYFf/OIX6dmz5/va9+GHH86RRx6ZN954I/X19YWOUWkiCwAAAAAAdEHHHXdcbrrppmzYsCH33XdfJk2alJ49e2bq1Klt9tu4cWN69erVLt/Zr1+/DnGM7cUzWQAAAAAAoAuqrq7OwIEDs/vuu+cLX/hCmpqacvfdd2fixIkZO3ZsLrvssgwePDh77bVXkmT58uU55ZRTUl9fn379+mXMmDF54YUXysfbvHlzpkyZkvr6+vTv3z9f+9rXUiqV2nzn6NGjc/7555ffb9iwIRdccEGGDBmS6urq7Lnnnrnxxhvzwgsv5Mgjj0ySfOhDH0pVVVUmTpz4jsd44403csYZZ+RDH/pQdtpppxx//PFZunRpefvNN9+c+vr6PPjggxk5cmR23nnnHHfccXn11Vfb9w/0HYgsAAAAAACwA+jdu3c2btyYJJk7d26WLFmShx56KPfcc09aWlpy7LHHpm/fvvnXf/3XPProo+VY8efPXHXVVbn55pvz4x//OI888khef/313HXXXe/6nWeccUZ++tOfZtasWXn22Wdzww03ZOedd86QIUPyj//4j0mSJUuW5NVXX833vve9dzzGxIkT89RTT+Xuu+/OggULUiqVcsIJJ6SlpaW8z1tvvZUrr7wyf//3f5/58+fnpZdeyle/+tX2+GN7V34uDAAAAAAAurBSqZS5c+fmwQcfzLnnnpvXXnstffr0yY9+9KPyz4T9wz/8Q1pbW/OjH/0oVVVVSZKbbrop9fX1efjhh3PMMcdk5syZmTp1ak4++eQkyezZs/Pggw9u8Xufe+653HnnnXnooYfS1NSUJPlv/+2/lbf/+WfBBgwY0OaZLP+vpUuX5u67786jjz6aT37yk0mSW2+9NUOGDMmcOXPy2c9+NknS0tKS2bNnZ4899kiSTJ48OdOmTSv6R/a+iSwAAAAAANAF3XPPPdl5553T0tKS1tbWfO5zn8sll1ySSZMmZb/99mvzHJZnnnkmzz//fPr27dvmGOvXr88f/vCHNDc359VXX82hhx5a3tajR4+MGjXqbT8Z9meLFy9O9+7d8xd/8ReFz+HZZ59Njx492nxv//79s9dee+XZZ58tr+20007lwJIkgwYNyqpVqwp/7/slsgAAAAAAQBd05JFH5vrrr0+vXr0yePDg9OjxX0mgT58+bfZdu3ZtDj744Nx6661vO86uu+5a6Pt79+5d6HNF9OzZs837qqqqLcaf9uSZLAAAAAAA0AX16dMne+65Z4YOHdomsLyTgw46KEuXLs2AAQOy5557tnnV1dWlrq4ugwYNyhNPPFH+zKZNm7Jo0aItHnO//fZLa2tr5s2b947b/3wnzebNm7d4jJEjR2bTpk1tvvc///M/s2TJkuyzzz7vek7bg8gCAAAAAAA7uPHjx2eXXXbJmDFj8q//+q9ZtmxZHn744Zx33nl5+eWXkyRf+tKXcsUVV2TOnDn5/e9/ny9+8YtZvXr1Fo85bNiwTJgwIZ///OczZ86c8jHvvPPOJMnuu++eqqqq3HPPPXnttdeydu3atx1jxIgRGTNmTM4+++w88sgjeeaZZ3L66afnwx/+cMaMGbNN/iy2hsgCAAAAAAA7uJ122inz58/P0KFDc/LJJ2fkyJE566yzsn79+tTW1iZJvvKVr+R//I//kQkTJqSxsTF9+/bNSSed9K7Hvf766/OZz3wmX/ziF7P33nvn7LPPzrp165IkH/7wh3PppZfmwgsvTENDQyZPnvyOx7jpppty8MEH51Of+lQaGxtTKpVy3333ve0nwiqhqrQ9fpSsg1uzZk3q6urS3Nxc/ocFAAC2hWEX3lvpEXgPL9R8rtIj8F4uaa70BADADmT9+vVZtmxZhg8fnpqamkqPQzt6t7+377cbuJMFAAAAAACgAJEFAAAAAACgAJEFAAAAAACgAJEFAAAAAACgAJEFAAAAAACgAJEFAAAAAADeQ6lUqvQItLP2+Hta0cgyf/78fPrTn87gwYNTVVWVOXPmlLe1tLTkggsuyH777Zc+ffpk8ODBOeOMM/LKK6+0Ocbrr7+e8ePHp7a2NvX19TnrrLOydu3a7XwmAAAAAAB0Rd27d0+SbNy4scKT0N7eeuutJEnPnj0LH6NHew1TxLp163LAAQfk85//fE4++eQ229566608/fTTueiii3LAAQfkjTfeyJe+9KX81V/9VZ566qnyfuPHj8+rr76ahx56KC0tLTnzzDNzzjnn5LbbbtvepwMAAAAAQBfTo0eP7LTTTnnttdfSs2fPdOvmB6I6u1KplLfeeiurVq1KfX19OaQVUVXqIPc4VVVV5a677srYsWO3uM/ChQvz8Y9/PC+++GKGDh2aZ599Nvvss08WLlyYUaNGJUkeeOCBnHDCCXn55ZczePDg9/Xda9asSV1dXZqbm1NbW9sepwMAAO9o2IX3VnoE3sMLNZ+r9Ai8l0uaKz0BALCD2bhxY5YtW5bW1tZKj0I7qq+vz8CBA1NVVfW2be+3G1T0Tpat1dzcnKqqqtTX1ydJFixYkPr6+nJgSZKmpqZ069YtTzzxRE466aQKTQoAAAAAQFfRq1evjBgxwk+GdSE9e/b8QHew/FmniSzr16/PBRdckL/+678uV6MVK1ZkwIABbfbr0aNH+vXrlxUrVmzxWBs2bMiGDRvK79esWbNthgYAAAAAoEvo1q1bampqKj0GHUyniCwtLS055ZRTUiqVcv3113/g402fPj2XXnppO0zW9fk5i47vhStOrPQIAAAAAAA7pA7/hJ4/B5YXX3wxDz30UJvfPhs4cGBWrVrVZv9Nmzbl9ddfz8CBA7d4zKlTp6a5ubn8Wr58+TabHwAAAAAA6Jo69J0sfw4sS5cuzb/8y7+kf//+bbY3NjZm9erVWbRoUQ4++OAkya9//eu0trbm0EMP3eJxq6urU11dvU1nBwAAAAAAuraKRpa1a9fm+eefL79ftmxZFi9enH79+mXQoEH5zGc+k6effjr33HNPNm/eXH7OSr9+/dKrV6+MHDkyxx13XM4+++zMnj07LS0tmTx5ck477bQMHjy4UqcFAAAAAADsACoaWZ566qkceeSR5fdTpkxJkkyYMCGXXHJJ7r777iTJgQce2OZz//Iv/5LRo0cnSW699dZMnjw5Rx99dLp165Zx48Zl1qxZ22V+AAAAAABgx1XRyDJ69OiUSqUtbn+3bX/Wr1+/3Hbbbe05FgAAAAAAwHvq8A++BwAAAAAA6IhEFgAAAAAAgAJEFgAAAAAAgAJEFgAAAAAAgAJEFgAAAAAAgAJ6VHoA4AO6pK7SE/BeLmmu9AQAAAAAwDbgThYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACRBYAAAAAAIACKhpZ5s+fn09/+tMZPHhwqqqqMmfOnDbbS6VSLr744gwaNCi9e/dOU1NTli5d2maf119/PePHj09tbW3q6+tz1llnZe3atdvxLAAAAAAAgB1RRSPLunXrcsABB+Taa699x+0zZszIrFmzMnv27DzxxBPp06dPjj322Kxfv768z/jx4/Pv//7veeihh3LPPfdk/vz5Oeecc7bXKQAAAAAAADuoHpX88uOPPz7HH3/8O24rlUqZOXNmvv71r2fMmDFJkltuuSUNDQ2ZM2dOTjvttDz77LN54IEHsnDhwowaNSpJ8v3vfz8nnHBCrrzyygwePHi7nQsAAAAAALBj6bDPZFm2bFlWrFiRpqam8lpdXV0OPfTQLFiwIEmyYMGC1NfXlwNLkjQ1NaVbt2554okntnjsDRs2ZM2aNW1eAAAAAAAAW6PDRpYVK1YkSRoaGtqsNzQ0lLetWLEiAwYMaLO9R48e6devX3mfdzJ9+vTU1dWVX0OGDGnn6QEAAAAAgK6uw0aWbWnq1Klpbm4uv5YvX17pkQAAAAAAgE6mw0aWgQMHJklWrlzZZn3lypXlbQMHDsyqVavabN+0aVNef/318j7vpLq6OrW1tW1eAAAAAAAAW6PDRpbhw4dn4MCBmTt3bnltzZo1eeKJJ9LY2JgkaWxszOrVq7No0aLyPr/+9a/T2tqaQw89dLvPDAAAAAAA7Dh6VPLL165dm+eff778ftmyZVm8eHH69euXoUOH5vzzz8+3vvWtjBgxIsOHD89FF12UwYMHZ+zYsUmSkSNH5rjjjsvZZ5+d2bNnp6WlJZMnT85pp52WwYMHV+isAAAAAACAHUFFI8tTTz2VI488svx+ypQpSZIJEybk5ptvzte+9rWsW7cu55xzTlavXp3DDz88DzzwQGpqasqfufXWWzN58uQcffTR6datW8aNG5dZs2Zt93MBAAAAAAB2LBWNLKNHj06pVNri9qqqqkybNi3Tpk3b4j79+vXLbbfdti3GAwAAAAAA2KIO+0wWAAAAAACAjkxkAQAAAAAAKEBkAQAAAAAAKEBkAQAAAAAAKEBkAQAAAAAAKEBkAQAAAAAAKEBkAQAAAAAAKEBkAQAAAAAAKEBkAQAAAAAAKKBHpQcAAAAAAKCLuqSu0hPwXi5prvQEnZo7WQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAoQWQAAAAAAAAroUekBAKA9DLvw3kqPwHt44YoTKz0CAAAAQLtyJwsAAAAAAEABIgsAAAAAAEABIgsAAAAAAEABnskCAGwfl9RVegLeyyXNlZ4AAAAAOhV3sgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABQgsgAAAAAAABTQoSPL5s2bc9FFF2X48OHp3bt39thjj3zzm99MqVQq71MqlXLxxRdn0KBB6d27d5qamrJ06dIKTg0AAAAAAOwIOnRk+fa3v53rr78+11xzTZ599tl8+9vfzowZM/L973+/vM+MGTMya9aszJ49O0888UT69OmTY489NuvXr6/g5AAAAAAAQFfXo9IDvJvHHnssY8aMyYknnpgkGTZsWH7605/mySefTPKnu1hmzpyZr3/96xkzZkyS5JZbbklDQ0PmzJmT0047rWKzAwAAAAAAXVuHvpPlk5/8ZObOnZvnnnsuSfLMM8/kkUceyfHHH58kWbZsWVasWJGmpqbyZ+rq6nLooYdmwYIFWzzuhg0bsmbNmjYvAAAAAACArdGh72S58MILs2bNmuy9997p3r17Nm/enMsuuyzjx49PkqxYsSJJ0tDQ0OZzDQ0N5W3vZPr06bn00ku33eAAAAAAAECX16HvZLnzzjtz66235rbbbsvTTz+dn/zkJ7nyyivzk5/85AMdd+rUqWlubi6/li9f3k4TAwAAAAAAO4oOfSfL3/7t3+bCCy8sP1tlv/32y4svvpjp06dnwoQJGThwYJJk5cqVGTRoUPlzK1euzIEHHrjF41ZXV6e6unqbzg4AAAAAAHRtHfpOlrfeeivdurUdsXv37mltbU2SDB8+PAMHDszcuXPL29esWZMnnngijY2N23VWAAAAAABgx9Kh72T59Kc/ncsuuyxDhw7Nvvvum3/7t3/L1Vdfnc9//vNJkqqqqpx//vn51re+lREjRmT48OG56KKLMnjw4IwdO7aywwMAAAAAAF1ah44s3//+93PRRRfli1/8YlatWpXBgwfnb/7mb3LxxReX9/na176WdevW5Zxzzsnq1atz+OGH54EHHkhNTU0FJwcAAAAAALq6Dh1Z+vbtm5kzZ2bmzJlb3KeqqirTpk3LtGnTtt9gAAAAAADADq9DP5MFAAAAAACgoxJZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAAChBZAAAAAAAACvhAkWXjxo1ZsmRJNm3a1F7zAAAAAAAAdAqFIstbb72Vs846KzvttFP23XffvPTSS0mSc889N1dccUW7DggAAAAAANARFYosU6dOzTPPPJOHH344NTU15fWmpqbccccd7TYcAAAAAABAR9WjyIfmzJmTO+64I5/4xCdSVVVVXt93333zhz/8od2GAwAAAAAA6KgK3cny2muvZcCAAW9bX7duXZvoAgAAAAAA0FUViiyjRo3KvffeW37/57Dyox/9KI2Nje0zGQAAAAAAQAdW6OfCLr/88hx//PH53e9+l02bNuV73/tefve73+Wxxx7LvHnz2ntGAAAAAACADqfQnSyHH354Fi9enE2bNmW//fbLr371qwwYMCALFizIwQcf3N4zAgAAAAAAdDiF7mRJkj322CM//OEP23MWAAAAoIMYduG9770TFfPCFSdWegQAIAXvZLnvvvvy4IMPvm39wQcfzP333/+BhwIAAAAAAOjoCt3JcuGFF+aKK65423qpVMqFF16Y448//gMPBgAAAMAWXFJX6Ql4L5c0V3oCALaDQneyLF26NPvss8/b1vfee+88//zzH3goAAAAAACAjq5QZKmrq8t//Md/vG39+eefT58+fT7wUAAAAAAAAB1docgyZsyYnH/++fnDH/5QXnv++efzla98JX/1V3/VbsMBAAAAAAB0VIUiy4wZM9KnT5/svffeGT58eIYPH56RI0emf//+ufLKK9t7RgAAAAAAgA6n0IPv6+rq8thjj+Whhx7KM888k969e2f//ffPEUcc0d7zAQAAAAAAdEiFIkuSVFVV5ZhjjskxxxzTnvMAAAAAAAB0Cu87ssyaNSvnnHNOampqMmvWrHfd97zzzvvAgwEAAAAAAHRk7zuyfPe738348eNTU1OT7373u1vcr6qqSmQBAAAAAAC6vPcdWZYtW/aOfw0AAAAAALAj6ra1H2hpackee+yRZ599dlvMAwAAAAAA0ClsdWTp2bNn1q9fvy1mAQAAAAAA6DS2OrIkyaRJk/Ltb387mzZtau95AAAAAAAAOoX3/UyW/9fChQszd+7c/OpXv8p+++2XPn36tNn+i1/8ol2GAwAAAAAA6KgKRZb6+vqMGzeuvWcBAAAAAADoNLYqsrS2tuY73/lOnnvuuWzcuDFHHXVULrnkkvTu3XtbzQcAAAAAANAhbdUzWS677LL83d/9XXbeeed8+MMfzqxZszJp0qRtNRsAAAAAAECHtVWR5ZZbbsl1112XBx98MHPmzMkvf/nL3HrrrWltbd1W8wEAAAAAAHRIWxVZXnrppZxwwgnl901NTamqqsorr7zS7oMBAAAAAAB0ZFsVWTZt2pSampo2az179kxLS0u7DgUAAAAAANDRbdWD70ulUiZOnJjq6ury2vr16/O//tf/Sp8+fcprv/jFL9pvQgAAAAAAgA5oqyLLhAkT3rZ2+umnt9swAAAAAAAAncVWRZabbrppW80BAAAAAADQqWzVM1kAAAAAAAD4E5EFAAAAAACgAJEFAAAAAACgAJEFAAAAAACggA4fWf73//7fOf3009O/f//07t07++23X5566qny9lKplIsvvjiDBg1K796909TUlKVLl1ZwYgAAAAAAYEfQoSPLG2+8kcMOOyw9e/bM/fffn9/97ne56qqr8qEPfai8z4wZMzJr1qzMnj07TzzxRPr06ZNjjz0269evr+DkAAAAAABAV9ej0gO8m29/+9sZMmRIbrrppvLa8OHDy39dKpUyc+bMfP3rX8+YMWOSJLfccksaGhoyZ86cnHbaadt9ZgAAAAAAYMfQoe9kufvuuzNq1Kh89rOfzYABA/Kxj30sP/zhD8vbly1blhUrVqSpqam8VldXl0MPPTQLFiyoxMgAAAAAAMAOokNHlv/4j//I9ddfnxEjRuTBBx/MF77whZx33nn5yU9+kiRZsWJFkqShoaHN5xoaGsrb3smGDRuyZs2aNi8AAAAAAICt0aF/Lqy1tTWjRo3K5ZdfniT52Mc+lt/+9reZPXt2JkyYUPi406dPz6WXXtpeYwIAAAAAADugDn0ny6BBg7LPPvu0WRs5cmReeumlJMnAgQOTJCtXrmyzz8qVK8vb3snUqVPT3Nxcfi1fvrydJwcAAAAAALq6Dh1ZDjvssCxZsqTN2nPPPZfdd989STJ8+PAMHDgwc+fOLW9fs2ZNnnjiiTQ2Nm7xuNXV1amtrW3zAgAAAAAA2Bod+ufCvvzlL+eTn/xkLr/88pxyyil58skn84Mf/CA/+MEPkiRVVVU5//zz861vfSsjRozI8OHDc9FFF2Xw4MEZO3ZsZYcHAAAAAAC6tA4dWQ455JDcddddmTp1aqZNm5bhw4dn5syZGT9+fHmfr33ta1m3bl3OOeecrF69OocffngeeOCB1NTUVHByAAAAAACgq+vQkSVJPvWpT+VTn/rUFrdXVVVl2rRpmTZt2nacCgAAAAAA2NF16GeyAAAAAAAAdFQiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAEiCwAAAAAAQAGdKrJcccUVqaqqyvnnn19eW79+fSZNmpT+/ftn5513zrhx47Jy5crKDQkAAAAAAOwQOk1kWbhwYW644Ybsv//+bda//OUv55e//GV+9rOfZd68eXnllVdy8sknV2hKAAAAAABgR9EpIsvatWszfvz4/PCHP8yHPvSh8npzc3NuvPHGXH311TnqqKNy8MEH56abbspjjz2Wxx9/vIITAwAAAAAAXV2niCyTJk3KiSeemKampjbrixYtSktLS5v1vffeO0OHDs2CBQu2eLwNGzZkzZo1bV4AAAAAAABbo0elB3gvt99+e55++uksXLjwbdtWrFiRXr16pb6+vs16Q0NDVqxYscVjTp8+PZdeeml7jwoAAAAAAOxAOvSdLMuXL8+XvvSl3HrrrampqWm3406dOjXNzc3l1/Lly9vt2AAAAAAAwI6hQ0eWRYsWZdWqVTnooIPSo0eP9OjRI/PmzcusWbPSo0ePNDQ0ZOPGjVm9enWbz61cuTIDBw7c4nGrq6tTW1vb5gUAAAAAALA1OvTPhR199NH5zW9+02btzDPPzN57750LLrggQ4YMSc+ePTN37tyMGzcuSbJkyZK89NJLaWxsrMTIAAAAAADADqJDR5a+ffvmox/9aJu1Pn36pH///uX1s846K1OmTEm/fv1SW1ubc889N42NjfnEJz5RiZEBAAAAAIAdRIeOLO/Hd7/73XTr1i3jxo3Lhg0bcuyxx+a6666r9FgAAAAAAEAX1+kiy8MPP9zmfU1NTa699tpce+21lRkIAAAAAADYIXXoB98DAAAAAAB0VCILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAASILAAAAAABAAR06skyfPj2HHHJI+vbtmwEDBmTs2LFZsmRJm33Wr1+fSZMmpX///tl5550zbty4rFy5skITAwAAAAAAO4oOHVnmzZuXSZMm5fHHH89DDz2UlpaWHHPMMVm3bl15ny9/+cv55S9/mZ/97GeZN29eXnnllZx88skVnBoAAAAAANgR9Kj0AO/mgQceaPP+5ptvzoABA7Jo0aIcccQRaW5uzo033pjbbrstRx11VJLkpptuysiRI/P444/nE5/4RCXGBgAAAAAAdgAd+k6W/19zc3OSpF+/fkmSRYsWpaWlJU1NTeV99t577wwdOjQLFizY4nE2bNiQNWvWtHkBAAAAAABsjU4TWVpbW3P++efnsMMOy0c/+tEkyYoVK9KrV6/U19e32behoSErVqzY4rGmT5+eurq68mvIkCHbcnQAAAAAAKAL6jSRZdKkSfntb3+b22+//QMfa+rUqWlubi6/li9f3g4TAgAAAAAAO5IO/UyWP5s8eXLuueeezJ8/P7vttlt5feDAgdm4cWNWr17d5m6WlStXZuDAgVs8XnV1daqrq7flyAAAAAAAQBfXoe9kKZVKmTx5cu666678+te/zvDhw9tsP/jgg9OzZ8/MnTu3vLZkyZK89NJLaWxs3N7jAgAAAAAAO5AOfSfLpEmTctttt+Wf/umf0rdv3/JzVurq6tK7d+/U1dXlrLPOypQpU9KvX7/U1tbm3HPPTWNjYz7xiU9UeHoAAAAAAKAr69CR5frrr0+SjB49us36TTfdlIkTJyZJvvvd76Zbt24ZN25cNmzYkGOPPTbXXXfddp4UAAAAAADY0XToyFIqld5zn5qamlx77bW59tprt8NEAAAAAAAAf9Khn8kCAAAAAADQUYksAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABYgsAAAAAAAABXSZyHLttddm2LBhqampyaGHHponn3yy0iMBAAAAAABdWJeILHfccUemTJmSb3zjG3n66adzwAEH5Nhjj82qVasqPRoAAAAAANBFdYnIcvXVV+fss8/OmWeemX322SezZ8/OTjvtlB//+MeVHg0AAAAAAOiielR6gA9q48aNWbRoUaZOnVpe69atW5qamrJgwYJ3/MyGDRuyYcOG8vvm5uYkyZo1a7btsJ1Q64a3Kj0C72FNVanSI/BeXFu2C9erjs/1qhNwvdouXK86PterTsD1artwverYXKs6Adcq+JMNrlcdnuvVO/pzLyiV3v2f4U4fWf74xz9m8+bNaWhoaLPe0NCQ3//+9+/4menTp+fSSy992/qQIUO2yYywLdVVegDe2xX+LkHietUpuF5BEterTsH1ClyrOgPXKqCzcL16V2+++Wbq6rb8Z9TpI0sRU6dOzZQpU8rvW1tb8/rrr6d///6pqqqq4GSwddasWZMhQ4Zk+fLlqa2trfQ4AFvkegV0Fq5XQGfgWgV0Fq5XdGalUilvvvlmBg8e/K77dfrIsssuu6R79+5ZuXJlm/WVK1dm4MCB7/iZ6urqVFdXt1mrr6/fViPCNldbW+t/qIBOwfUK6Cxcr4DOwLUK6Cxcr+is3u0Olj/r9A++79WrVw4++ODMnTu3vNba2pq5c+emsbGxgpMBAAAAAABdWae/kyVJpkyZkgkTJmTUqFH5+Mc/npkzZ2bdunU588wzKz0aAAAAAADQRXWJyHLqqafmtddey8UXX5wVK1bkwAMPzAMPPJCGhoZKjwbbVHV1db7xjW+87efvADoa1yugs3C9AjoD1yqgs3C9YkdQVSqVSpUeAgAAAAAAoLPp9M9kAQAAAAAAqASRBQAAAAAAoACRBQAAAAAAoACRBQAAAAAAoACRBTqxa6+9NsOGDUtNTU0OPfTQPPnkk5UeCaCN+fPn59Of/nQGDx6cqqqqzJkzp9IjAbzN9OnTc8ghh6Rv374ZMGBAxo4dmyVLllR6LIC3uf7667P//vuntrY2tbW1aWxszP3331/psQDe0xVXXJGqqqqcf/75lR4F2p3IAp3UHXfckSlTpuQb3/hGnn766RxwwAE59thjs2rVqkqPBlC2bt26HHDAAbn22msrPQrAFs2bNy+TJk3K448/noceeigtLS055phjsm7dukqPBtDGbrvtliuuuCKLFi3KU089laOOOipjxozJv//7v1d6NIAtWrhwYW644Ybsv//+lR4FtomqUqlUqvQQwNY79NBDc8ghh+Saa65JkrS2tmbIkCE599xzc+GFF1Z4OoC3q6qqyl133ZWxY8dWehSAd/Xaa69lwIABmTdvXo444ohKjwPwrvr165fvfOc7Oeussyo9CsDbrF27NgcddFCuu+66fOtb38qBBx6YmTNnVnosaFfuZIFOaOPGjVm0aFGamprKa926dUtTU1MWLFhQwckAADq/5ubmJH/6F5cAHdXmzZtz++23Z926dWlsbKz0OADvaNKkSTnxxBPb/Dss6Gp6VHoAYOv98Y9/zObNm9PQ0NBmvaGhIb///e8rNBUAQOfX2tqa888/P4cddlg++tGPVnocgLf5zW9+k8bGxqxfvz4777xz7rrrruyzzz6VHgvgbW6//fY8/fTTWbhwYaVHgW1KZAEAAPi/Jk2alN/+9rd55JFHKj0KwDvaa6+9snjx4jQ3N+fnP/95JkyYkHnz5gktQIeyfPnyfOlLX8pDDz2UmpqaSo8D25TIAp3QLrvsku7du2flypVt1leuXJmBAwdWaCoAgM5t8uTJueeeezJ//vzstttulR4H4B316tUre+65Z5Lk4IMPzsKFC/O9730vN9xwQ4UnA/gvixYtyqpVq3LQQQeV1zZv3pz58+fnmmuuyYYNG9K9e/cKTgjtxzNZoBPq1atXDj744MydO7e81tramrlz5/otXgCArVQqlTJ58uTcdddd+fWvf53hw4dXeiSA9621tTUbNmyo9BgAbRx99NH5zW9+k8WLF5dfo0aNyvjx47N48WKBhS7FnSzQSU2ZMiUTJkzIqFGj8vGPfzwzZ87MunXrcuaZZ1Z6NICytWvX5vnnny+/X7ZsWRYvXpx+/fpl6NChFZwM4L9MmjQpt912W/7pn/4pffv2zYoVK5IkdXV16d27d4WnA/gvU6dOzfHHH5+hQ4fmzTffzG233ZaHH344Dz74YKVHA2ijb9++b3u+XZ8+fdK/f3/PvaPLEVmgkzr11FPz2muv5eKLL86KFSty4IEH5oEHHkhDQ0OlRwMoe+qpp3LkkUeW30+ZMiVJMmHChNx8880Vmgqgreuvvz5JMnr06DbrN910UyZOnLj9BwLYglWrVuWMM87Iq6++mrq6uuy///558MEH85d/+ZeVHg0AdlhVpVKpVOkhAAAAAAAAOhvPZAEAAAAAAChAZAEAAAAAAChAZAEAAAAAAChAZAEAAAAAAChAZAEAAAAAAChAZAEAAAAAAChAZAEAAAAAAChAZAEAAAAAAChAZAEAADqtiRMnZuzYsW9bf/jhh1NVVZXVq1dv95kAAIAdh8gCAAAAAABQgMgCAAB0ef/4j/+YfffdN9XV1Rk2bFiuuuqqNturqqoyZ86cNmv19fW5+eabkyQbN27M5MmTM2jQoNTU1GT33XfP9OnTy/uuXr06//N//s/suuuuqa2tzVFHHZVnnnlmW58WAABQYT0qPQAAAMC2tGjRopxyyim55JJLcuqpp+axxx7LF7/4xfTv3z8TJ058X8eYNWtW7r777tx5550ZOnRoli9fnuXLl5e3f/azn03v3r1z//33p66uLjfccEOOPvroPPfcc+nXr982OjMAAKDSRBYAAKBTu+eee7Lzzju3Wdu8eXP5r6+++uocffTRueiii5IkH/nIR/K73/0u3/nOd953ZHnppZcyYsSIHH744amqqsruu+9e3vbII4/kySefzKpVq1JdXZ0kufLKKzNnzpz8/Oc/zznnnPMBzxAAAOio/FwYAADQqR155JFZvHhxm9ePfvSj8vZnn302hx12WJvPHHbYYVm6dGmbGPNuJk6cmMWLF2evvfbKeeedl1/96lflbc8880zWrl2b/v37Z+eddy6/li1blj/84Q/tc5IAAECH5E4WAACgU+vTp0/23HPPNmsvv/zyVh2jqqoqpVKpzVpLS0v5rw866KAsW7Ys999/f/75n/85p5xySpqamvLzn/88a9euzaBBg/Lwww+/7bj19fVbNQcAANC5iCwAAECXNnLkyDz66KNt1h599NF85CMfSffu3ZMku+66a1599dXy9qVLl+att95q85na2tqceuqpOfXUU/OZz3wmxx13XF5//fUcdNBBWbFiRXr06JFhw4Zt8/MBAAA6DpEFAADo0r7yla/kkEMOyTe/+c2ceuqpWbBgQa655ppcd9115X2OOuqoXHPNNWlsbMzmzZtzwQUXpGfPnuXtV199dQYNGpSPfexj6datW372s59l4MCBqa+vT1NTUxobGzN27NjMmDEjH/nIR/LKK6/k3nvvzUknnZRRo0ZV4rQBAIDtwDNZAACALu2ggw7KnXfemdtvvz0f/ehHc/HFF2fatGltHnp/1VVXZciQIfnv//2/53Of+1y++tWvZqeddipv79u3b2bMmJFRo0blkEMOyQsvvJD77rsv3bp1S1VVVe67774cccQROfPMM/ORj3wkp512Wl588cU0NDRU4IwBAIDtpar0///wMAAAAAAAAO/JnSwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAFiCwAAAAAAAAF/B8Kh2eTtAw+xAAAAABJRU5ErkJggg==\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "otUgdX-2PgGq"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}