# -*- coding: utf-8 -*-
"""multiple_linear_regression_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9Mddxo0bC2ltaio-meTKztSnKZp3VBm
"""

import numpy as np

import matplotlib.pyplot as plt

x_train = np.array([
    [2104, 5, 1, 45],
    [1416, 3, 2 , 40],
    [852, 2, 1, 35]
])

y_train= np.array([460, 232, 178])

w_init= np.array([0.2, 10, -20, -2])

b_init = 30

print(f"Feature (x): \n {x_train}")

print(f"w_inti: {w_init}")
print(f"b_int: {b_init}")

'''def predict_for_loop(x, w ,b):
  n = x.shape[0]
  p=0
  for i in range(0,n):
    p_i= x[i] * w[i]
    p= p + p_i
  p = p + b
  return p'''

def predict_vactorized(x, w, b):
  return np.dot(w,x)+b


all_predict= np.matmul(x_train, w_init)+b_init


plt.figure(figsize=(8,5))
x_indi= np.arange(len(y_train))
width= 0.25



plt.bar(x_indi - width/2, y_train, width, label="actual")
plt.bar(x_indi + width/2, all_predict, width, label="predicted")

plt.xlabel("House ID")
plt.ylabel("price ")
plt.xticks(x_indi, ['House 1', 'House 2', 'House 3'])
plt.legend()
plt.grid(axis='y', alpha = 0.5)
plt.show()

